
name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latst
    steps:
    - name: Print greeting
      run: echo "Hello World!"
    - name: Print goodbye
      run: echo "Don bye"
